apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service
  namespace: jose2317
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: inventory-service
  type: LoadBalancer